spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zagzag?serverTimezone=UTC
    username: root
    password: policegml1!
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update